### PR TITLE
Fix first token whitespace

### PR DESCRIPTION
**Pull request by nwoythal**
Continuing work from https://github.com/puppetlabs/puppet-lint/pull/83 by adding tests

Resolves https://github.com/puppetlabs/puppet-lint/issues/81

### CODE REVIEW

**Comment by nwoythal** [comment]
Having issues creating a proper ticket -- seems something is fishy with signing up a new account via tickets.puppetlabs.com :shrug:

**Comment by ekohl** [comment]
I'm not sure an issue is really needed.

**Comment by chelnak** [comment]
Here is the right place for community tickets these days 😊.

**Comment by chelnak** [comment]
Small nit. Would it be possible to rebase on main rather than having the merge commit?

**Review by chelnak — APPROVED** [review]

**Comment by chelnak** [comment]
@ekohl Are you happy with this as a continuation of your work?

**Review by ekohl — APPROVED** [review]
Yes, thanks @nwoythal for adding tests.

**Pull request merged**
