### PR TITLE
Fix legacy facts check

### PR DESCRIPTION
**Pull request by danifr**
Fix for https://github.com/puppetlabs/puppet-lint/issues/106

@chelnak I know this is not is not very elegant but I think it is the simplest change I can do without needing to change puppet-lint's code much. Let me know.

### CODE REVIEW

**Comment by chelnak** [comment]
@danifr I think we need to investigate this.

Would you be able to provide the following debug info form your environment:

`gem list | grep puppet-lint`

pdk-templates version as listed in your `metadata.json`

**Comment by danifr** [comment]
I am using 3.3.0, but this issue is very easy to reproduce. 
Just create a new file with a top level legacy fact like for example `$::fqdn`

```
danielfr@latdfr /t/test (master)> cat test.pp
class role_infra::test {
  apache::vhost {'https.test_reports':
    servername      => $::fqdn,
  }
}
```

Apply puppet-lint to fix it...

```
danielfr@latdfr /t/test (master)> puppet-lint --fix test.pp 
ERROR: role_infra::test not in autoload module layout on line 1 (check: autoloader_layout)
WARNING: class not documented on line 1 (check: documentation)
FIXED: legacy fact 'fqdn' on line 3 (check: legacy_facts)
FIXED: top scope fact instead of facts hash on line 3 (check: top_scope_facts)
```

The resulting output is wrong.

```
danielfr@latdfr /t/test (master) [1]> cat test.pp
class role_infra::test {
  apache::vhost {'https.test_reports':
    servername      => $facts['facts['networking']['fqdn']'],
  }
}
```

**Comment by danifr** [comment]
Sure. 
```
~> gem list | grep puppet-lint
puppet-lint (3.3.0)
```

Not sure what you mean with:
`pdk-templates version as listed in your metadata.json`

**Comment by chelnak** [comment]
@danifr Thanks! It's interesting that your gem list is not listing any plugins or additional versions.

That throws out one of my theories.

@GSPatton is going to try and replicate this today.

**Comment by danifr** [comment]
Thanks, let me know in case I can help with something else :)

**Comment by danifr** [comment]
Ah, nice thank you very much :) 

Are you planning on releasing a new version including the patch? or shall I get the files directly and try them on my local installation?

**Pull request closed without merging**
