### PR TITLE
Fix puppet-lint namespace clash with new puppetlabs-lint gem

### PR DESCRIPTION
**Pull request by GSPatton**
Currently, the new puppet-lint gem and the old one clash as both compete for the PuppetLint namespace. This initial commit aims to solve this by intorducing the puppetlabs directory in lib so that resources are found in lib/puppetlabs/puppet-lint rather than lib/puppet-lint. This method is being tested first to avoid introducing changes that would require users to update their puppet-lint resource definitions

## Summary
Provide a detailed description of all the changes present in this pull request.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@GSPatton can you please rebase? I think we should test one of the external plugins with this branch before merging.

**Comment by GSPatton** [comment]
hi @bastelfreak. Will test that out now

**Review by ekohl — CHANGES_REQUESTED** [review]
I think **all** instances of `PuppetLint` need to be changed as well, otherwise it still overlaps with `puppet-lint` and can accidentally load the wrong files.

**Comment by ekohl** [comment]
Just a thought: perhaps pick a name that really is different, like `puppet-cop` (after RuboCop).

**Comment by GSPatton** [comment]
Hi @ekohl, instead of changing all instances of `PuppetLint` we added the `puppetlabs` directory into `lib` to change the directory structure and thereby hopefully not overlap namespaces with the old gem. This has been tested and works. But please test it out and let us know if you find anything.

**Comment by jordanbreen28** [comment]
Closing in favour of

**Pull request closed without merging**
